version: '3.8'

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - GITEA__webhook__ALLOWED_HOST_LIST=*
    ports:
      - "3000:3000"
    volumes:
      - gitea-data:/data
    networks:
      - devops-net

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitea
    networks:
      - devops-net

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - devops-net

  # --- BLUE ENVIRONMENT (ACTIVE INITIALLY) ---
  backend-blue:
    build: ./backend
    container_name: backend-blue
    networks:
      - devops-net

  frontend-blue:
    build: ./frontend
    container_name: frontend-blue
    depends_on:
      - backend-blue
    environment:
      - BACKEND_URL=http://backend-blue:4000
    networks:
      - devops-net

  # --- GREEN ENVIRONMENT (IDLE INITIALLY) ---
  backend-green:
    build: ./backend
    container_name: backend-green
    networks:
      - devops-net

  frontend-green:
    build: ./frontend
    container_name: frontend-green
    depends_on:
      - backend-green
    environment:
      - BACKEND_URL=http://backend-green:4000
    networks:
      - devops-net

  # --- LOAD BALANCER ---
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # This is the main entry point for users
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend-blue
      - frontend-green
    networks:
      - devops-net

volumes:
  gitea-data:
  jenkins-data:
  nexus-data:

networks:
  devops-net:
    driver: bridge
    name: devops-net